version: "3.9"

services:
  server:
    environment:
      - NODE_ENV=local
    hostname: semilla_server
    container_name: semilla_server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - 5500:5500
    command: >
      sh -c "npm run dev"
    volumes:
      - ./src/src:/app/src


