version: "3.9"

services:
  server:
    environment:
      - NODE_ENV=local
    hostname: semilla_server
    container_name: semilla_server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - 5500:5500
    command: >
      sh -c "npm run dev"
    volumes:
      - ./src/src:/app/src
  
  mongo-db:
    image: mongo:7.0.6
    restart: unless-stopped
    hostname: database
    container_name: database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: proyecto
      MONGO_INITDB_ROOT_PASSWORD: reto
    volumes:
      - ./mongo/:/data/db



